# Generated by Django 4.2.11 on 2025-06-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_blog_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
