# Generated by Django 4.2.11 on 2025-06-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_about_me_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
