# Generated by Django 4.2.11 on 2025-06-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_about_me_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='live_demo_url',
            new_name='UrlPortfolio',
        ),
        migrations.AddField(
            model_name='blog',
            name='UrlBlog',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
