# Generated by Django 4.2.11 on 2025-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
